/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultisigWallet } from "./MultisigWallet";
export * as factories from "./factories";
export { MultisigWallet__factory } from "./factories/MultisigWallet__factory";
