/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultisigWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmSignerUpdate"
      | "confirmTransaction"
      | "executeSignerUpdate"
      | "executeTransaction"
      | "getSigners"
      | "getTransaction"
      | "getTransactionCount"
      | "isConfirmed"
      | "isSigner"
      | "isSignerUpdateConfirmed"
      | "signerUpdates"
      | "signers"
      | "submitSignerUpdate"
      | "submitTransaction"
      | "threshold"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfirmTransaction"
      | "ExecuteTransaction"
      | "RevokeConfirmation"
      | "SignerSetUpdateConfirmed"
      | "SignerSetUpdateExecuted"
      | "SignerSetUpdateSubmitted"
      | "SubmitTransaction"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmSignerUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSignerUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isConfirmed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSignerUpdateConfirmed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerUpdates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSignerUpdate",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmSignerUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSignerUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSignerUpdateConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSignerUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace ConfirmTransactionEvent {
  export type InputTuple = [owner: AddressLike, txIndex: BigNumberish];
  export type OutputTuple = [owner: string, txIndex: bigint];
  export interface OutputObject {
    owner: string;
    txIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecuteTransactionEvent {
  export type InputTuple = [owner: AddressLike, txIndex: BigNumberish];
  export type OutputTuple = [owner: string, txIndex: bigint];
  export interface OutputObject {
    owner: string;
    txIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokeConfirmationEvent {
  export type InputTuple = [owner: AddressLike, txIndex: BigNumberish];
  export type OutputTuple = [owner: string, txIndex: bigint];
  export interface OutputObject {
    owner: string;
    txIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerSetUpdateConfirmedEvent {
  export type InputTuple = [signer: AddressLike, updateIndex: BigNumberish];
  export type OutputTuple = [signer: string, updateIndex: bigint];
  export interface OutputObject {
    signer: string;
    updateIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerSetUpdateExecutedEvent {
  export type InputTuple = [updateIndex: BigNumberish];
  export type OutputTuple = [updateIndex: bigint];
  export interface OutputObject {
    updateIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerSetUpdateSubmittedEvent {
  export type InputTuple = [
    updateIndex: BigNumberish,
    newSigners: AddressLike[],
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [
    updateIndex: bigint,
    newSigners: string[],
    newThreshold: bigint
  ];
  export interface OutputObject {
    updateIndex: bigint;
    newSigners: string[];
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmitTransactionEvent {
  export type InputTuple = [
    owner: AddressLike,
    txIndex: BigNumberish,
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    owner: string,
    txIndex: bigint,
    to: string,
    value: bigint,
    data: string
  ];
  export interface OutputObject {
    owner: string;
    txIndex: bigint;
    to: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultisigWallet extends BaseContract {
  connect(runner?: ContractRunner | null): MultisigWallet;
  waitForDeployment(): Promise<this>;

  interface: MultisigWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmSignerUpdate: TypedContractMethod<
    [_updateIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmTransaction: TypedContractMethod<
    [_txIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeSignerUpdate: TypedContractMethod<
    [_updateIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [_txIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  getTransaction: TypedContractMethod<
    [_txIndex: BigNumberish],
    [
      [string, bigint, string, boolean, bigint] & {
        to: string;
        value: bigint;
        data: string;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;

  getTransactionCount: TypedContractMethod<[], [bigint], "view">;

  isConfirmed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isSigner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isSignerUpdateConfirmed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  signerUpdates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        newThreshold: bigint;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;

  signers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  submitSignerUpdate: TypedContractMethod<
    [_newSigners: AddressLike[], _newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitTransaction: TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  threshold: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint] & {
        to: string;
        value: bigint;
        data: string;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmSignerUpdate"
  ): TypedContractMethod<[_updateIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmTransaction"
  ): TypedContractMethod<[_txIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSignerUpdate"
  ): TypedContractMethod<[_updateIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<[_txIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [_txIndex: BigNumberish],
    [
      [string, bigint, string, boolean, bigint] & {
        to: string;
        value: bigint;
        data: string;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isConfirmed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSignerUpdateConfirmed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "signerUpdates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        newThreshold: bigint;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitSignerUpdate"
  ): TypedContractMethod<
    [_newSigners: AddressLike[], _newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitTransaction"
  ): TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint] & {
        to: string;
        value: bigint;
        data: string;
        executed: boolean;
        numConfirmations: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ConfirmTransaction"
  ): TypedContractEvent<
    ConfirmTransactionEvent.InputTuple,
    ConfirmTransactionEvent.OutputTuple,
    ConfirmTransactionEvent.OutputObject
  >;
  getEvent(
    key: "ExecuteTransaction"
  ): TypedContractEvent<
    ExecuteTransactionEvent.InputTuple,
    ExecuteTransactionEvent.OutputTuple,
    ExecuteTransactionEvent.OutputObject
  >;
  getEvent(
    key: "RevokeConfirmation"
  ): TypedContractEvent<
    RevokeConfirmationEvent.InputTuple,
    RevokeConfirmationEvent.OutputTuple,
    RevokeConfirmationEvent.OutputObject
  >;
  getEvent(
    key: "SignerSetUpdateConfirmed"
  ): TypedContractEvent<
    SignerSetUpdateConfirmedEvent.InputTuple,
    SignerSetUpdateConfirmedEvent.OutputTuple,
    SignerSetUpdateConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "SignerSetUpdateExecuted"
  ): TypedContractEvent<
    SignerSetUpdateExecutedEvent.InputTuple,
    SignerSetUpdateExecutedEvent.OutputTuple,
    SignerSetUpdateExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SignerSetUpdateSubmitted"
  ): TypedContractEvent<
    SignerSetUpdateSubmittedEvent.InputTuple,
    SignerSetUpdateSubmittedEvent.OutputTuple,
    SignerSetUpdateSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SubmitTransaction"
  ): TypedContractEvent<
    SubmitTransactionEvent.InputTuple,
    SubmitTransactionEvent.OutputTuple,
    SubmitTransactionEvent.OutputObject
  >;

  filters: {
    "ConfirmTransaction(address,uint256)": TypedContractEvent<
      ConfirmTransactionEvent.InputTuple,
      ConfirmTransactionEvent.OutputTuple,
      ConfirmTransactionEvent.OutputObject
    >;
    ConfirmTransaction: TypedContractEvent<
      ConfirmTransactionEvent.InputTuple,
      ConfirmTransactionEvent.OutputTuple,
      ConfirmTransactionEvent.OutputObject
    >;

    "ExecuteTransaction(address,uint256)": TypedContractEvent<
      ExecuteTransactionEvent.InputTuple,
      ExecuteTransactionEvent.OutputTuple,
      ExecuteTransactionEvent.OutputObject
    >;
    ExecuteTransaction: TypedContractEvent<
      ExecuteTransactionEvent.InputTuple,
      ExecuteTransactionEvent.OutputTuple,
      ExecuteTransactionEvent.OutputObject
    >;

    "RevokeConfirmation(address,uint256)": TypedContractEvent<
      RevokeConfirmationEvent.InputTuple,
      RevokeConfirmationEvent.OutputTuple,
      RevokeConfirmationEvent.OutputObject
    >;
    RevokeConfirmation: TypedContractEvent<
      RevokeConfirmationEvent.InputTuple,
      RevokeConfirmationEvent.OutputTuple,
      RevokeConfirmationEvent.OutputObject
    >;

    "SignerSetUpdateConfirmed(address,uint256)": TypedContractEvent<
      SignerSetUpdateConfirmedEvent.InputTuple,
      SignerSetUpdateConfirmedEvent.OutputTuple,
      SignerSetUpdateConfirmedEvent.OutputObject
    >;
    SignerSetUpdateConfirmed: TypedContractEvent<
      SignerSetUpdateConfirmedEvent.InputTuple,
      SignerSetUpdateConfirmedEvent.OutputTuple,
      SignerSetUpdateConfirmedEvent.OutputObject
    >;

    "SignerSetUpdateExecuted(uint256)": TypedContractEvent<
      SignerSetUpdateExecutedEvent.InputTuple,
      SignerSetUpdateExecutedEvent.OutputTuple,
      SignerSetUpdateExecutedEvent.OutputObject
    >;
    SignerSetUpdateExecuted: TypedContractEvent<
      SignerSetUpdateExecutedEvent.InputTuple,
      SignerSetUpdateExecutedEvent.OutputTuple,
      SignerSetUpdateExecutedEvent.OutputObject
    >;

    "SignerSetUpdateSubmitted(uint256,address[],uint256)": TypedContractEvent<
      SignerSetUpdateSubmittedEvent.InputTuple,
      SignerSetUpdateSubmittedEvent.OutputTuple,
      SignerSetUpdateSubmittedEvent.OutputObject
    >;
    SignerSetUpdateSubmitted: TypedContractEvent<
      SignerSetUpdateSubmittedEvent.InputTuple,
      SignerSetUpdateSubmittedEvent.OutputTuple,
      SignerSetUpdateSubmittedEvent.OutputObject
    >;

    "SubmitTransaction(address,uint256,address,uint256,bytes)": TypedContractEvent<
      SubmitTransactionEvent.InputTuple,
      SubmitTransactionEvent.OutputTuple,
      SubmitTransactionEvent.OutputObject
    >;
    SubmitTransaction: TypedContractEvent<
      SubmitTransactionEvent.InputTuple,
      SubmitTransactionEvent.OutputTuple,
      SubmitTransactionEvent.OutputObject
    >;
  };
}
